# .goreleaser.yml
# Build customization
dist: goreleaser-build
builds:
  - main: main.go
    binary: mouthful
    id: mouthful-linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      pre: ./goreleaser-pre.sh
  - main: main.go
    id: mouthful-windows-amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    binary: mouthful
    goos:
      - windows
    goarch:
      - amd64
  - main: ./cmd/spoon/main.go
    id: spoon-linux-amd64
    binary: spoon
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      pre: ./goreleaser-pre.sh
  - main: ./cmd/spoon/main.go
    id: spoon-windows-amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    binary: spoon
    goos:
      - windows
    goarch:
      - amd64
# Archive customization
archives:
  -
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - ./static/*
      - ./data/config.json
